# Generated by Django 4.1.1 on 2022-09-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributevalue',
            name='value_file',
        ),
        migrations.RemoveField(
            model_name='attributevalue',
            name='value_image',
        ),
        migrations.AlterField(
            model_name='attribute',
            name='attribute_type',
            field=models.CharField(choices=[('text', 'Text'), ('int', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('date', 'Date'), ('time', 'Time'), ('datetime', 'Datetime'), ('url', 'URL'), ('email', 'Email')], max_length=100),
        ),
    ]
